import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(__dirname, '../..')

function read(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

describe('UX-leadership enablement artifacts', () => {
  const researchPath = 'docs/research/2026-07-06-enablement-author-tailored-github-agents-md-role-specialized.md'
  const planPath = 'docs/plans/2026-07-06-enablement-author-tailored-github-agents-md-role-specialized.md'
  const devlogPath = 'blog/2026-07-06-enablement-agent-roles/index.html'
  const changedArtifacts = [
    researchPath,
    planPath,
    'AGENTS.md',
    '.github/copilot-instructions.md',
    devlogPath
  ]

  it('keeps the competitor benchmark, current-gallery ratings, and testable backlog together', () => {
    const research = read(researchPath)

    for (const competitor of ['SnapGene', 'Benchling', 'Chromas', 'FinchTV', 'ApE']) {
      expect(research).toContain(competitor)
    }

    expect(research).toContain('Rated current-state screenshot UX gallery')
    expect(research).toContain('Prioritized, testable improvement backlog')
    expect(research).toContain('Frictionless first run proof')
    expect(research).toContain('Design-token convergence')
    expect(research).toContain('Power-preserving panel work')
  })

  it('defines each role with the gates needed for small no-regression PRs', () => {
    const plan = read(planPath)

    for (const role of [
      'ux-designer.md',
      'accessibility.md',
      'performance.md',
      'test-author.md',
      'code-reviewer.md',
      'devlog-writer.md'
    ]) {
      expect(plan).toContain(role)
    }

    for (const gate of [
      'WCAG 2.1 AA',
      'npm run perf:smoke',
      'Do not skip, stub, or weaken existing tests',
      'editing, export, alignment, assembly, primer/Tm, permalinks, and multi-trace',
      'blog/index.html',
      'vite.config.ts'
    ]) {
      expect(plan).toContain(gate)
    }
  })

  it('updates repository guidance and devlog wiring for the enablement wave', () => {
    expect(read('AGENTS.md')).toContain('current UX-gallery screenshots')
    expect(read('.github/copilot-instructions.md')).toContain('Keep PRs small, screenshot-gated, devlog-updated')
    expect(read(devlogPath)).toContain('role-specialized UX-leadership enablement')
    expect(read('blog/index.html')).toContain('2026-07-06-enablement-agent-roles')
    expect(read('vite.config.ts')).toContain('blogEnablementAgentRolesEntry')
  })

  it('keeps enablement copy free of attribution-sensitive wording', () => {
    const forbidden = [/\bClaude\b/i, /\bAnthropic\b/i, /\bLLM\b/i, /Generated by/i, /\bAI-assisted\b/i]

    for (const artifact of changedArtifacts) {
      const content = read(artifact)
      for (const pattern of forbidden) {
        expect(content, `${artifact} should not match ${pattern}`).not.toMatch(pattern)
      }
    }
  })
})
